In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
pd.set_option('display.max_columns', 500)

## 1. Inspecting the dataset

In [3]:
path = '../raw/dirty'

In [4]:
dirty = pd.read_csv(path+'/diabetes-dirty.csv', sep=';')

In [5]:
dirty.head()

,Unnamed: 0,Index,Pregnancies,Glucose,Blood Pressure,Skin Thickness,Insulin,Body Mass Index,Diabetes Pedigree Function,Age,Outcome,BMI Category,Clinic Region,Care Path,Patient Segment
0,0,0,6,148.0 mg/dL,72.0,35.0,nan uU/mL,33.6 bmi,0.627,50.0 years,positive,obese,north,high-risk,adult
1,1,1,1,85.0,66.0,29.0,NaN,26.6,0.351,31.0,negative,OVERWEIGHT,SOUTH,ROUTINE FOLLOW-UP,SENIOR
2,2,2,8,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1,normal-weight,N,urgent monitoring,mid-age
3,3,3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0,under wt,south-side,routine,?
4,4,4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1,unknown,?,NaN,Adult

In [6]:
dirty.columns

Index(['Unnamed: 0', ' Index ', 'Pregnancies ', ' Glucose', 'Blood Pressure',
       'Skin Thickness ', 'Insulin', 'Body Mass Index',
       'Diabetes Pedigree Function', 'Age ', 'Outcome ', 'BMI Category',
       'Clinic Region', 'Care Path ', 'Patient Segment'],
      dtype='str')

In [7]:
dirty = dirty.drop(columns=['Unnamed: 0', ' Index '])

In [8]:
dirty.shape

(771, 13)

In [9]:
dirty.info()

<class 'pandas.DataFrame'>
RangeIndex: 771 entries, 0 to 770
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pregnancies                 771 non-null    int64
 1    Glucose                    714 non-null    str
 2   Blood Pressure              666 non-null    float64
 3   Skin Thickness              543 non-null    float64
 4   Insulin                     425 non-null    str
 5   Body Mass Index             718 non-null    str
 6   Diabetes Pedigree Function  771 non-null    float64
 7   Age                         709 non-null    str
 8   Outcome                     744 non-null    str
 9   BMI Category                686 non-null    str
 10  Clinic Region               744 non-null    str
 11  Care Path                   721 non-null    str
 12  Patient Segment             744 non-null    str
dtypes: float64(3), int64(1), str(9)
memory usage: 78.4 KB

In [10]:
dirty.describe()

,Pregnancies,Blood Pressure,Skin Thickness,Diabetes Pedigree Function
count,771.000000,666.000000,543.000000,771.000000
mean,3.836576,72.231231,29.116022,0.471516
std,3.373966,12.294530,10.478557,0.330866
min,-2.000000,24.000000,7.000000,0.078000
25%,1.000000,64.000000,22.000000,0.243500
50%,3.000000,72.000000,29.000000,0.374000
75%,6.000000,80.000000,36.000000,0.625000
max,17.000000,122.000000,99.000000,2.420000

## 2. Preprocessing

In [11]:
dirty.columns = [col.strip() for col in dirty.columns]
dirty.columns

Index(['Pregnancies', 'Glucose', 'Blood Pressure', 'Skin Thickness', 'Insulin',
       'Body Mass Index', 'Diabetes Pedigree Function', 'Age', 'Outcome',
       'BMI Category', 'Clinic Region', 'Care Path', 'Patient Segment'],
      dtype='str')

In [12]:
cat_list = list(dirty.select_dtypes(include='object').columns)
cat_list

C:\Users\aikyu\AppData\Local\Temp\ipykernel_5060\3528442749.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_list = list(dirty.select_dtypes(include='object').columns)

['Glucose',
 'Insulin',
 'Body Mass Index',
 'Age',
 'Outcome',
 'BMI Category',
 'Clinic Region',
 'Care Path',
 'Patient Segment']

In [13]:
num_list = list(dirty.select_dtypes(include='number').columns)
num_list

['Pregnancies',
 'Blood Pressure',
 'Skin Thickness',
 'Diabetes Pedigree Function']

In [14]:
(dirty.isna().sum()/len(dirty)*100).sort_values(ascending=False)

Insulin                       44.876783
Skin Thickness                29.571984
Blood Pressure                13.618677
BMI Category                  11.024643
Age                            8.041505
Glucose                        7.392996
Body Mass Index                6.874189
Care Path                      6.485084
Clinic Region                  3.501946
Patient Segment                3.501946
Outcome                        3.501946
Pregnancies                    0.000000
Diabetes Pedigree Function     0.000000
dtype: float64

In [15]:
(dirty[num_list].isna().sum()/len(dirty)*100).sort_values(ascending=False)

Skin Thickness                29.571984
Blood Pressure                13.618677
Pregnancies                    0.000000
Diabetes Pedigree Function     0.000000
dtype: float64

## 3. Standardizing categorical values

In [16]:
for c in cat_list:
    print(c, dirty[c].unique(), end='\n\n')

Glucose <StringArray>
['148.0 mg/dL',        '85.0',       '183.0',        '89.0',       '137.0',
          ' ?',        '78.0',       '115.0',       '197.0',       '125.0',
 ...
 '136.0 mg/dL',       '167.0', '195.0 mg/dL',       '169.0',       '366.0',
       '375.0',       '402.0',        '65.0',       '459.0',       '190.0']
Length: 175, dtype: str

Insulin <StringArray>
['nan uU/mL',         nan,      '94.0',     '168.0',        ' ?',      '88.0',
     '543.0',     '846.0',     '175.0',     '230.0',
 ...
     '387.0',      '22.0',    '1455.0',     '392.0',     '178.0',     '127.0',
     '370.0',     '510.0',      '16.0',     '112.0']
Length: 195, dtype: str

Body Mass Index <StringArray>
['33.6 bmi',     '26.6',     '23.3',   ' 28.1 ',     '43.1',       ' ?',
     '31.0',     '35.3',   ' 30.5 ',        nan,
 ...
   ' 28.5 ',    '101.5',     '49.3',   ' 46.3 ',   ' 31.2 ',     '97.5',
   ' 43.3 ',   ' 36.3 ',     '37.5',   ' 28.4 ']
Length: 340, dtype: str

Age <StringArray>
[ '50.0 years',        '31.0',        '32.0',        '21.0',        '33.0',
        '30.0',        '26.0',           nan,        '53.0',        '54.0',
        '34.0',        '57.0',        '59.0',        '51.0',       '396.0',
        '27.0',        '50.0',        '41.0',        '29.0',        '43.0',
  '22.0 years',        '38.0',       '720.0',        '28.0',        '22.0',
        '45.0',        '35.0',        '56.0',        '48.0',         '150',
        '24.0',        '58.0',  '42.0 years',       '492.0',        '44.0',
        '39.0',        '36.0',        '42.0',        '25.0',        '23.0',
        '37.0',        '60.0',        '40.0',  '25.0 years',        '46.0',
        '61.0',        '69.0',       '276.0',       '360.0',        '62.0',
  '31.0 years',        '55.0',        '65.0',        '47.0',  '27.0 years',
        '52.0',       '384.0',        '66.0',  '33.0 years',        '49.0',
        '63.0',  '38.0 years',       '480.0',       '624.0',       '564.0',
       '372.0',  '24.0 years',       '420.0',       '348.0',  '21.0 years',
  '30.0 years',       '552.0',       '336.0',  '32.0 years',  '26.0 years',
       '264.0',       '516.0',       '312.0',        '72.0',  '81.0 years',
 '252.0 years',        '67.0',       '252.0',       '300.0',  '43.0 years',
       '444.0',  '46.0 years',  '34.0 years',       '288.0',  '28.0 years',
        '70.0',        '68.0',       '408.0',  '52.0 years',       '540.0',
  '39.0 years']
Length: 96, dtype: str

Outcome <StringArray>
['positive', ' negative ', '1 ', '0', '1', '?', nan]
Length: 7, dtype: str

BMI Category <StringArray>
[      ' obese ',    'OVERWEIGHT', 'normal-weight',      'under wt',
       'unknown',    'overweight',         'OBESE',             nan,
         'obese',        'normal',         ' nan ',           'NAN',
        'NORMAL',  ' overweight ',         ' NAN ',      ' normal ',
       ' OBESE ',   'UNDERWEIGHT',  ' OVERWEIGHT ',   'underweight']
Length: 20, dtype: str

Clinic Region <StringArray>
['north ', 'SOUTH', 'N', 'south-side', ' ?', 'South', 'North', nan]
Length: 8, dtype: str

Care Path <StringArray>
[        'high-risk', 'ROUTINE FOLLOW-UP', 'urgent monitoring',
          'routine ',                 nan, 'Routine Follow-up',
         'High Risk']
Length: 7, dtype: str

Patient Segment <StringArray>
['adult ', 'SENIOR', 'mid-age', ' ?', 'Adult', nan, 'Senior']
Length: 7, dtype: str

In [17]:
replacements = {
    '1 ': '1',
    'positive': '1',
    'negative': '0',
    ' negative ': '0',
    '?': np.nan,
    'normal-weight': 'normal',
    'under wt': 'underweight',
    'unknown': np.nan,
    ' nan ': np.nan,
    'NAN': np.nan,
    ' NAN ': np.nan,
    'north ': 'North',
    'SOUTH': 'South',
    'N': 'North',
    'south-side': 'South',
    ' ?': np.nan,
    'High Risk': 'high-risk'
}

In [18]:
for c in cat_list:
    dirty[c] = dirty[c].replace(replacements)
    print(c, dirty[c].unique(), end='\n\n')

Glucose <StringArray>
['148.0 mg/dL',        '85.0',       '183.0',        '89.0',       '137.0',
           nan,        '78.0',       '115.0',       '197.0',       '125.0',
 ...
 '136.0 mg/dL',       '167.0', '195.0 mg/dL',       '169.0',       '366.0',
       '375.0',       '402.0',        '65.0',       '459.0',       '190.0']
Length: 174, dtype: str

Insulin <StringArray>
['nan uU/mL',         nan,      '94.0',     '168.0',      '88.0',     '543.0',
     '846.0',     '175.0',     '230.0',      '83.0',
 ...
     '387.0',      '22.0',    '1455.0',     '392.0',     '178.0',     '127.0',
     '370.0',     '510.0',      '16.0',     '112.0']
Length: 193, dtype: str

Body Mass Index <StringArray>
['33.6 bmi',     '26.6',     '23.3',   ' 28.1 ',     '43.1',        nan,
     '31.0',     '35.3',   ' 30.5 ',     '37.6',
 ...
   ' 28.5 ',    '101.5',     '49.3',   ' 46.3 ',   ' 31.2 ',     '97.5',
   ' 43.3 ',   ' 36.3 ',     '37.5',   ' 28.4 ']
Length: 338, dtype: str

Age <StringArray>
[ '50.0 years',        '31.0',        '32.0',        '21.0',        '33.0',
        '30.0',        '26.0',           nan,        '53.0',        '54.0',
        '34.0',        '57.0',        '59.0',        '51.0',       '396.0',
        '27.0',        '50.0',        '41.0',        '29.0',        '43.0',
  '22.0 years',        '38.0',       '720.0',        '28.0',        '22.0',
        '45.0',        '35.0',        '56.0',        '48.0',         '150',
        '24.0',        '58.0',  '42.0 years',       '492.0',        '44.0',
        '39.0',        '36.0',        '42.0',        '25.0',        '23.0',
        '37.0',        '60.0',        '40.0',  '25.0 years',        '46.0',
        '61.0',        '69.0',       '276.0',       '360.0',        '62.0',
  '31.0 years',        '55.0',        '65.0',        '47.0',  '27.0 years',
        '52.0',       '384.0',        '66.0',  '33.0 years',        '49.0',
        '63.0',  '38.0 years',       '480.0',       '624.0',       '564.0',
       '372.0',  '24.0 years',       '420.0',       '348.0',  '21.0 years',
  '30.0 years',       '552.0',       '336.0',  '32.0 years',  '26.0 years',
       '264.0',       '516.0',       '312.0',        '72.0',  '81.0 years',
 '252.0 years',        '67.0',       '252.0',       '300.0',  '43.0 years',
       '444.0',  '46.0 years',  '34.0 years',       '288.0',  '28.0 years',
        '70.0',        '68.0',       '408.0',  '52.0 years',       '540.0',
  '39.0 years']
Length: 96, dtype: str

Outcome <StringArray>
['1', '0', nan]
Length: 3, dtype: str

BMI Category <StringArray>
[     ' obese ',   'OVERWEIGHT',       'normal',  'underweight',
            nan,   'overweight',        'OBESE',        'obese',
       'NORMAL', ' overweight ',     ' normal ',      ' OBESE ',
  'UNDERWEIGHT', ' OVERWEIGHT ']
Length: 14, dtype: str

Clinic Region <StringArray>
['North', 'South', nan]
Length: 3, dtype: str

Care Path <StringArray>
[        'high-risk', 'ROUTINE FOLLOW-UP', 'urgent monitoring',
          'routine ',                 nan, 'Routine Follow-up']
Length: 6, dtype: str

Patient Segment <StringArray>
['adult ', 'SENIOR', 'mid-age', nan, 'Adult', 'Senior']
Length: 6, dtype: str

In [19]:
to_lower = ['BMI Category', 'Care Path', 'Patient Segment']

In [20]:
for c in to_lower:
    dirty[c] = dirty[c].str.strip().str.lower()
    print(c, dirty[c].unique(), end='\n\n')

BMI Category <StringArray>
['obese', 'overweight', 'normal', 'underweight', nan]
Length: 5, dtype: str

Care Path <StringArray>
['high-risk', 'routine follow-up', 'urgent monitoring', 'routine', nan]
Length: 5, dtype: str

Patient Segment <StringArray>
['adult', 'senior', 'mid-age', nan]
Length: 4, dtype: str

## 4. Fixing column types

In [21]:
shouldbe_num = ['Glucose', 'Insulin', 'Body Mass Index', 'Age']

In [22]:
for c in shouldbe_num:
    dirty[c] = pd.to_numeric(dirty[c].astype(str).str.split(' ').str[0], errors='coerce')
    dirty[c] = dirty[c].fillna(dirty[c].median())
    print(c, dirty[c].unique(), end='\n\n')

Glucose [148.  85. 183.  89. 137. 119.  78. 115. 197. 125. 999. 168. 139. 189.
 166. 100. 118. 103. 126.  99. 196. 143. 147. 145. 117. 109. 158.  88.
  92. 122. 138. 102.  90. 111. 180. 133. 106. 171. 159.  71. 105. 528.
 150.  73. 187. 146.  84. 399.  44. 141. 114. 129.  62.  95. 131. 112.
 113.  74.  83. 101. 110. 136. 107.  80. 123.  81. 134. 142. 144. 279.
 163. 151.  96. 155.  76. 160. 124.  97. 162. 132. 120. 173. 170.  93.
 384. 108. 154.  57. 156. 153. 188. 152. 104.  87.  79.  75. 130. 194.
 181. 128. 135. 324. 184. 179. 140. 177. 513. 543.  91. 417. 165.  86.
 191. 161. 501.  77. 182. 456. 157. 178. 116.  61. 270.  98. 127.  82.
 193.  72. 172.  94. 175. 195.  68. 252. 186. 164. 567. 198. 121. 363.
 176.  67. 174. 309. 167. 169. 366. 375. 402.  65. 459. 190.]

Insulin [ 126.   94.  168.   88.  543.  846.  175.  230.   83.   96.  146.  115.
  140.  110.  245.   54.  192.  207.   70.  240.   82.   36.   23. 1500.
  342.  304.  142.  128.  100.   90.  270.   71.  125.  176.   48.   64.
  228.   76.  320.   40.  152.   18.  135.  495.   37.   51.   99.  225.
   49.   50.   92.  325.   63.  284.  119.  204.  155.  485.  114.  105.
  285.  156.  130.   55.   58.  160.  210.  318.   44.  190.  280.   87.
  271.  129.  120.  478.   56.   32.  744.   53.   45.  194.  680.  402.
  258.  150.   67.   57.  116.  278.  122.  545.  220.   74.  360.  215.
  184.   42.  132.  148.  180.  205.   85.  231.  145.   68.   52.  255.
   73.  108.  167.  249.  293.   66.  465.   89.   84.   75.   72.  182.
   59.   81.  196.  415.  275.  165.  579.  310.   61.  170.   78.  277.
   60.   14.   95.  237.  191.  328.  250.  480.  265.  193.   79.   86.
  326.  188.  106.   65.  166.  274.   77.  330.  600.  185.   25.   41.
 1360.  158.  321.  144.   15.  183.   91.   46.  760.  440.  159.  540.
  200. 1000.  387.   22. 1455.  392.  178.  127.  370.  510.   16.  112.]

Body Mass Index [ 33.6   26.6   23.3   32.4   43.1   31.    35.3   37.6   38.    27.1
  30.1   25.8   30.    29.6   43.3   39.3   35.4   39.8   36.6   -5.
  39.4   23.2   22.2   34.1   36.    24.8   19.9   27.6   24.    33.2
  32.9   38.2   37.1   34.    40.2   22.7   45.4   27.4   42.    39.1
  24.2   24.4   84.25  34.7   46.8   40.5   82.25  25.    25.4   32.8
  29.    32.5   42.7   19.6   28.6   43.4   35.1   32.    24.7   32.6
  37.7   43.2   29.3   26.5   46.7   23.8   33.9   31.6   20.4   71.75
  49.7   39.    22.5   39.6   28.7   22.4   29.5   34.3   37.4   33.3
  31.2   30.5   28.2   34.2   55.    42.9   27.9   29.7   38.3   30.8
  36.9   52.75  39.5   27.3   21.9   40.6   47.9   50.    24.6   25.2
  37.2   44.2   29.9   31.9   28.9   43.5   67.1   45.    27.7   26.8
  35.9   22.6   33.1   52.3   24.3   22.9   34.8   30.9   68.25  23.9
  35.5   42.8   42.6   41.8   35.8   37.8   34.6   28.8   35.7   36.7
  44.   109.    89.75  44.1   18.4   29.2   64.    25.9   36.3   40.
  25.1   27.5   23.    24.9   25.3   37.9   30.4   27.    45.6   20.8
  28.    30.7   52.9   39.7   25.5   26.2   19.3   38.1   23.5   67.
  25.6   45.5   23.1   32.7   33.8   39.9   36.8   38.5   21.8   68.
  36.5   29.8   34.9   21.    38.4   39.2   48.3   20.    32.3   45.7
  22.1   21.1   35.    42.1   42.4   27.2   18.2   26.4   45.3   37.
  24.5   32.2   21.2   27.8   46.1   41.3   33.7   42.3   46.5   26.1
  33.5   26.    37.3   21.7   36.4   34.5   43.6   71.25  26.9   38.6
  31.3   66.25  38.7   34.4   67.75  23.7   35.2   28.4   19.5  103.75
  20.1   40.8   40.9   69.    28.3   57.3   35.6   49.6   44.6   24.1
  41.2   66.    44.5  101.5   49.3   97.5   37.5 ]

Age [ 50.  31.  32.  21.  33.  30.  26.  53.  54.  34.  57.  59.  51. 396.
  27.  41.  29.  43.  22.  38. 720.  28.  45.  35.  56.  48. 150.  24.
  58.  42. 492.  44.  39.  36.  25.  23.  37.  60.  40.  46.  61.  69.
 276. 360.  62.  55.  65.  47.  52. 384.  66.  49.  63. 480. 624. 564.
 372. 420. 348. 552. 336. 264. 516. 312.  72.  81. 252.  67. 300. 444.
 288.  70.  68. 408. 540.]

In [23]:
dirty.info()

<class 'pandas.DataFrame'>
RangeIndex: 771 entries, 0 to 770
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pregnancies                 771 non-null    int64
 1   Glucose                     771 non-null    float64
 2   Blood Pressure              666 non-null    float64
 3   Skin Thickness              543 non-null    float64
 4   Insulin                     771 non-null    float64
 5   Body Mass Index             771 non-null    float64
 6   Diabetes Pedigree Function  771 non-null    float64
 7   Age                         771 non-null    float64
 8   Outcome                     728 non-null    str
 9   BMI Category                650 non-null    str
 10  Clinic Region               724 non-null    str
 11  Care Path                   721 non-null    str
 12  Patient Segment             703 non-null    str
dtypes: float64(7), int64(1), str(5)
memory usage: 78.4 KB

## 5. Missing value imputation

In [24]:
cat_list = list(set(cat_list) - set(shouldbe_num))
num_list = num_list + shouldbe_num
cat_list, num_list

(['Care Path', 'Outcome', 'BMI Category', 'Clinic Region', 'Patient Segment'],
 ['Pregnancies',
  'Blood Pressure',
  'Skin Thickness',
  'Diabetes Pedigree Function',
  'Glucose',
  'Insulin',
  'Body Mass Index',
  'Age'])

In [25]:
(dirty[num_list].isna().sum()/len(dirty)*100).sort_values(ascending=False)

Skin Thickness                29.571984
Blood Pressure                13.618677
Pregnancies                    0.000000
Diabetes Pedigree Function     0.000000
Glucose                        0.000000
Insulin                        0.000000
Body Mass Index                0.000000
Age                            0.000000
dtype: float64

In [26]:
dirty['Skin Thickness'] = dirty['Skin Thickness'].fillna(dirty['Skin Thickness'].median())
dirty['Blood Pressure'] = dirty['Blood Pressure'].fillna(dirty['Blood Pressure'].median())

In [27]:
(dirty[num_list].isna().sum()/len(dirty)*100).sort_values(ascending=False)

Pregnancies                   0.0
Blood Pressure                0.0
Skin Thickness                0.0
Diabetes Pedigree Function    0.0
Glucose                       0.0
Insulin                       0.0
Body Mass Index               0.0
Age                           0.0
dtype: float64

In [28]:
(dirty[cat_list].isna().sum()/len(dirty)*100).sort_values(ascending=False)

BMI Category       15.693904
Patient Segment     8.819715
Care Path           6.485084
Clinic Region       6.095979
Outcome             5.577173
dtype: float64

In [29]:
for c in cat_list:
    dirty[c] = dirty[c].fillna('unknown')

In [30]:
(dirty[cat_list].isna().sum()/len(dirty)*100).sort_values(ascending=False)

Care Path          0.0
Outcome            0.0
BMI Category       0.0
Clinic Region      0.0
Patient Segment    0.0
dtype: float64

In [31]:
dirty.info()

<class 'pandas.DataFrame'>
RangeIndex: 771 entries, 0 to 770
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pregnancies                 771 non-null    int64
 1   Glucose                     771 non-null    float64
 2   Blood Pressure              771 non-null    float64
 3   Skin Thickness              771 non-null    float64
 4   Insulin                     771 non-null    float64
 5   Body Mass Index             771 non-null    float64
 6   Diabetes Pedigree Function  771 non-null    float64
 7   Age                         771 non-null    float64
 8   Outcome                     771 non-null    str
 9   BMI Category                771 non-null    str
 10  Clinic Region               771 non-null    str
 11  Care Path                   771 non-null    str
 12  Patient Segment             771 non-null    str
dtypes: float64(7), int64(1), str(5)
memory usage: 78.4 KB

## 6. Duplicates and outliers

In [32]:
dirty.duplicated().sum()

np.int64(3)

In [33]:
dirty[dirty.duplicated(keep=False)] #???

,Pregnancies,Glucose,Blood Pressure,Skin Thickness,Insulin,Body Mass Index,Diabetes Pedigree Function,Age,Outcome,BMI Category,Clinic Region,Care Path,Patient Segment
3,1,89.0,66.0,23.0,94.0,32.4,0.167,21.0,0,underweight,South,routine,unknown
15,7,100.0,72.0,29.0,126.0,30.0,0.484,32.0,1,overweight,South,high-risk,adult
27,1,119.0,72.0,15.0,140.0,23.2,0.487,22.0,0,obese,South,routine follow-up,adult
768,1,89.0,66.0,23.0,94.0,32.4,0.167,21.0,0,underweight,South,routine,unknown
769,7,100.0,72.0,29.0,126.0,30.0,0.484,32.0,1,overweight,South,high-risk,adult
770,1,119.0,72.0,15.0,140.0,23.2,0.487,22.0,0,obese,South,routine follow-up,adult

In [34]:
def verify_outliers(df, col):
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    outliers = (df[col] < (q1 - 1.5 * iqr)) | (df[col] > (q3 + 1.5 * iqr))
    if outliers.sum() > 0:
        return True
    return False

In [35]:
for c in num_list:
    print(verify_outliers(dirty,c))

True
True
True
True
True
True
True
True

In [36]:
dirty[dirty['Pregnancies']==-2]

,Pregnancies,Glucose,Blood Pressure,Skin Thickness,Insulin,Body Mass Index,Diabetes Pedigree Function,Age,Outcome,BMI Category,Clinic Region,Care Path,Patient Segment
63,-2,141.0,58.0,34.0,128.0,25.4,0.699,24.0,0,obese,South,high-risk,adult

In [37]:
dirty['Pregnancies'] = dirty['Pregnancies'].replace(-2, 2)
dirty.iloc[63]

Pregnancies                           2
Glucose                           141.0
Blood Pressure                     58.0
Skin Thickness                     34.0
Insulin                           128.0
Body Mass Index                    25.4
Diabetes Pedigree Function        0.699
Age                                24.0
Outcome                               0
BMI Category                      obese
Clinic Region                     South
Care Path                     high-risk
Patient Segment                   adult
Name: 63, dtype: object

## 7. Preparing the dataset for Ingestion Pipelines

In [38]:
dirty.sample(5)

,Pregnancies,Glucose,Blood Pressure,Skin Thickness,Insulin,Body Mass Index,Diabetes Pedigree Function,Age,Outcome,BMI Category,Clinic Region,Care Path,Patient Segment
489,8,194.0,80.0,29.0,126.0,26.1,0.551,67.0,0,overweight,South,routine,senior
767,1,119.0,70.0,31.0,126.0,30.4,0.315,23.0,1,normal,South,routine follow-up,adult
734,2,119.0,75.0,29.0,126.0,23.3,0.560,53.0,0,normal,North,urgent monitoring,senior
581,6,109.0,60.0,27.0,126.0,32.4,0.206,27.0,0,unknown,South,high-risk,adult
480,3,158.0,70.0,30.0,328.0,35.5,0.344,35.0,1,obese,North,high-risk,adult

In [39]:
dirty.to_csv('diabetes-clean.csv', index=False)